name: Demo CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: set props
        working-directory: spring/demo
        run: echo "${{ secrets.APPLICATION }}" >> ./src/main/resources/application.properties

      - name: confirm props
        working-directory: spring/demo
        run: cat ./src/main/resources/application.properties

      - name: grant exe
        working-directory: spring/demo
        run: chmod +x gradlew

      - name: build with gradle
        working-directory: spring/demo
        run: ./gradlew clean build -x test

      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.WAS }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: scp jar to was
        run: |
          scp spring/demo/build/libs/*.jar ec2-user@${{ secrets.WAS }}:/home/ec2-user/workspace/hana4/
