name: Demo CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    steps:
      - name: grant exe
        run: chmod +x gradlew

      - name: build with gradle
        run: ./gradlew clean build
