name: Demo CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: listing
        working-directory: spring/demo
        run: ls -al

      - name: grant exe
        working-directory: spring/demo
        run: chmod +x gradlew

      - name: build with gradle
        working-directory: spring/demo
        run: ./gradlew clean build
