name: Demo CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: mv to demo
        run: cd spring/demo

      - name: grant exe
        run: chmod +x gradlew

      - name: build with gradle
        run: ./gradlew clean build
