name: Demo CI/CD
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: setup node pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: setup pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Install Node
        uses: actions/setup-node@v4
        working-directory: my-app
        with:
          node-version: 21
          cache: "pnpm"

      - name: Install dependencies
        working-directory: my-app
        run: pnpm install

      - name: Build with Next.js
        working-directory: my-app
        run: pnpm next build

      - name: zip next
        working-directory: my-app
        run: zip -r next.zip .next

#      - name: set props
#        working-directory: spring/demo
#        run: echo "${{ secrets.APPLICATION }}" >> ./src/main/resources/application.properties

#      - name: grant exe
#        working-directory: spring/demo
#        run: chmod +x gradlew
#
#      - name: build with gradle
#        working-directory: spring/demo
#        run: ./gradlew clean build -x test

      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.WAS }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

#      - name: scp jar to was
#        run: |
#          scp spring/demo/build/libs/*.jar ec2-user@${{ secrets.WAS }}:/home/ec2-user/workspace/hana4.jar
#
#      - name: restart java
#        run: |
#          ssh ec2-user@${{ secrets.WAS }} '
#            cd /home/ec2-user/bin &&
#            ./restart.sh
#          '

      - name: scp jar to was
        run: |
          scp spring/demo/build/libs/*.jar ec2-user@${{ secrets.WAS }}:/home/ec2-user/workspace/hana4.jar

      - name: restart java
        run: |
          ssh ec2-user@${{ secrets.WAS }} '
            cd /home/ec2-user/bin &&
            ./restart.sh
          '

      - name: scp next to was
        run: |
          scp my-app/next.zip ec2-user@${{ secrets.WAS }}:/home/ec2-user/workspace/
